apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
 #this password is encoded with base64, if you want to provide it in string, use the below:
stringData:
  server: database-server
  
